field: 9efe44fe-2a14-4f10-81f7-75be0c8fbdc7
fieldLayouts:
  7a0966b7-b51b-4b4b-b47d-e240c1f0cc5d:
    tabs:
      -
        elements:
          -
            fieldUid: 36519940-9679-46e5-a452-bfcfc4df5fbe
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  36519940-9679-46e5-a452-bfcfc4df5fbe:
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: ''
    name: Images
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:c651db94-71b8-4347-9724-e5c9429c8afd'
      defaultUploadLocationSubpath: '{owner.slug}'
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:c651db94-71b8-4347-9724-e5c9429c8afd'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:c651db94-71b8-4347-9724-e5c9429c8afd'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: images
name: Images
sortOrder: 2
