baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Regnet Craft Mix'
primary: true
siteGroup: e60ff90f-3857-47f6-8c28-d7b5ccde0ebc # Regnet Craft Mix
sortOrder: 1
