dateModified: 1624363665
email:
  fromEmail: $SYSTEM_EMAIL_ADDRESS
  fromName: 'Regnet Craft Mix'
  replyToEmail: $REPLY_TO_ADDRESS
  template: null
  transportSettings:
    encryptionMethod: ''
    host: $SMTP_HOST
    password: $SMTP_PASS
    port: $SMTP_PORT
    timeout: '10'
    useAuthentication: '1'
    username: $SMTP_USER
  transportType: craft\mail\transportadapters\Smtp
plugins:
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  imgixer:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.2.0
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
  svgplaceholder:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Regnet Craft Mix'
  schemaVersion: 3.6.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
