enableVersioning: true
handle: error
name: Error
propagationMethod: all
siteSettings:
  ae36b6fe-f844-4187-8149-171ac89797bb: # Regnet Craft Mix
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
